name: Run
description: Run Action

inputs:
  environment:
    description: "Run environment"
    required: true
  databricks_client_id:
    description: "Databricks OAuth client ID"
    required: true
  databricks_client_secret:
    description: "Databricks OAuth client secret"
    required: true
  databricks_job:
    description: "Databricks job name to be executed"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: databricks/setup-cli@main
      with:
        version: 0.222.0

    - name: Run
      shell: bash
      working-directory: .
      env:
        DATABRICKS_CLIENT_ID: ${{ inputs.databricks_client_id }}
        DATABRICKS_CLIENT_SECRET: ${{ inputs.databricks_client_secret }}
        DATABRICKS_BUNDLE_ENV: ${{ inputs.environment }}
      run: |
        databricks bundle run ${{inputs.databricks_job}} --restart
